### PR TITLE
Urls for django 1.10

### PR DESCRIPTION
**Pull request by nicbus**
Please include this small fix and bump version so pip will be able to install a django 1.10 compatible version.

### CODE REVIEW

**Comment by azaghal** [comment]
Hi. Thanks for sending in the pull request. I just realised you're second person sending one in, so I'll try to get a new release out during this week. Hopefully I can have it support the LTS as well. :)

**Comment by nicbus** [comment]
Happy to hear you're still maintaining on the project!
Looking forward to the new version from pip ;-)

**Comment by azaghal** [comment]
Ok, done a quick test against Django 1.8 + Django 1.10. Seems to work fine, just had to apply the same type of change in testproject.

I'll also need to update Django version in requirements (so probably just going to mark it as Django >= 1.8 for now).

Since I maintain my own repo and issue tracker, I might close this pull request once the changes have been made, and mirror it to Github (pull requests/issue reports over Github are still welcome, just a bit of manual work on my side to sync them to my own infra :)

I'll probably push the new version on Friday (atm a bit preoccupied :)

**Comment by azaghal** [comment]
Of course, it might happen I lied a bit and that release is made tomorrow... On the positive side, it should also include support for transparency once I update pydenticon as well.

**Comment by azaghal** [comment]
Whoops, clicked the wrong button.

**Comment by azaghal** [comment]
Ok, merged the changes and created release. Attribution has been applied via git's --author flag.

**Pull request closed without merging**
